// Generated by CoffeeScript 1.3.3
(function() {
  var app, connect, express, game, http, io, server;

  express = require('express');

  http = require('http');

  connect = require('connect');

  io = require('socket.io');

  app = express();

  game = require('./lib/game');

  app.use(express.bodyParser());

  app.set('port', 1338);

  server = http.createServer(app);

  server.listen(app.get('port'), function() {
    return console.log('Express server listening on port ' + app.get('port'));
  });

  app.configure(function() {
    app.use('/public', express["static"](__dirname + '/public'));
    return app.use(express["static"](__dirname + '/public'));
  });

  game.inRange = function(evt) {
    return console.log(evt);
  };

  io = require('socket.io').listen(server);

  io.sockets.on('connection', function(socket) {
    socket.emit('news', {
      hello: 'world'
    });
    socket.on('error', function(data) {
      return console.log(data);
    });
    socket.on('start', function(data) {
      console.log('start');
      return game.start();
    });
    socket.on('stop', function() {
      return game.stop();
    });
    socket.on('kick', function(data) {
      var velocity;
      velocity = data.z;
      game.kick(velocity);
      return game.switchPlayer();
    });
    return game.inRange(function() {
      var id, players, whosTurn;
      players = io.sockets.clients();
      whosTurn = Math.floor(Math.random() * players.length);
      id = players[whosTurn].id;
      console.log(id);
      return io.sockets.socket(id).emit('turn');
    });
  });

}).call(this);
