// Generated by CoffeeScript 1.3.3
(function() {
  var app, connect, express, http, io, server;

  express = require('express');

  http = require('http');

  connect = require('connect');

  io = require('socket.io');

  app = express();

  app.use(express.bodyParser());

  app.set('port', 1337);

  server = http.createServer(app);

  server.listen(app.get('port'), function() {
    return console.log('Express server listening on port ' + app.get('port'));
  });

  app.configure(function() {
    app.use('/public', express["static"](__dirname + '/public'));
    return app.use(express["static"](__dirname + '/public'));
  });

  /*
  Socket.io
  */


  io = require('socket.io').listen(server);

  io.sockets.on('connection', function(socket) {
    socket.emit('news', {
      hello: 'world'
    });
    socket.on('my other event', function(data) {
      return console.log(data);
    });
    return socket.on('error', function(data) {
      return console.log(data);
    });
  });

}).call(this);
