// Generated by CoffeeScript 1.3.3
(function() {
  var app, connect, express, game, http, io, server;

  express = require('express');

  http = require('http');

  connect = require('connect');

  io = require('socket.io');

  app = express();

  game = require('./lib/game');

  app.use(express.bodyParser());

  app.set('port', 1338);

  server = http.createServer(app);

  server.listen(app.get('port'), function() {
    return console.log('Express server listening on port ' + app.get('port'));
  });

  app.configure(function() {
    app.use('/public', express["static"](__dirname + '/public'));
    return app.use(express["static"](__dirname + '/public'));
  });

  io = require('socket.io').listen(server);

  io.sockets.on('connection', function(socket) {
    socket.emit('news', {
      hello: 'world'
    });
    socket.on('my other event', function(data) {
      return io.sockets.emit('weeej', {
        mek: 'DUDE'
      });
    });
    socket.on('error', function(data) {
      return console.log(data);
    });
    socket.on('start', function(data) {
      console.log('start');
      return game.start();
    });
    socket.on('stop', function() {
      return game.stop();
    });
    return socket.on('kick', function() {
      return game.kick(8);
    });
  });

}).call(this);
